export function questions() {
    const worldQuestions = [
        "What is the origin and evolution of the universe?",
        "How does globalization impact international relations and culture?",
        "What are the ethical implications of emerging technologies?",
        "What is the impact of colonialism and imperialism on the world today?",
        "How does the brain process and interpret information?",
        "What are the causes and effects of biodiversity loss?",
        "What are the major historical events that shaped the modern world?",
        "How do different artistic movements reflect cultural values and beliefs?",
        "What are the basic principles of sports training and performance?",
        "How do animals communicate and interact with each other?",
        "What are the psychological factors that influence human behavior and decision-making?",
        "What are the key principles and techniques used in architecture and urban planning?",
        "How does popular culture reflect and shape societal norms and values?",
        "What are the causes and consequences of income inequality and poverty?",
        "How does the environment impact human health and wellbeing?",
        "What are the key principles and techniques used in music composition and performance?",
        "What are the major political and social movements of the 20th century?",
        "How do different cultures and societies define and value education?",
        "What are the basic principles and techniques used in culinary arts?",
        "How does transportation technology shape urban development and mobility?",
        "What is the nature of consciousness and subjective experience?",
        "How do economic systems impact the distribution of wealth and resources?",
        "What are the major social and cultural issues facing the world today?",
        "How does immigration impact global demographics and culture?",
        "What are the key principles and techniques used in filmmaking?",
        "What are the causes and effects of major pandemics and epidemics?",
        "How does social media shape public opinion and behavior?",
        "What are the causes and consequences of war and conflict?",
        "How do different types of renewable energy sources work?",
        "What are the fundamental principles of mathematics and logic?",
        "How do different cultures view and practice spirituality and religion?",
        "What are the key principles and techniques used in photography?",
        "What are the basic principles and techniques used in graphic design?",
        "How do human rights laws and treaties impact global society?",
        "What are the major cultural and scientific contributions of different civilizations?",
        "What are the key principles and techniques used in dance performance and choreography?",
        "How does globalization impact the environment and natural resources?",
        "What are the causes and consequences of major social and political revolutions?",
        "How do different societies view and approach mental health and wellness?",
        "What are the fundamental principles and techniques used in painting?",
        "What are the cultural and historical roots of different cuisines?",
        "How does gender identity and sexuality influence social dynamics?",
        "What are the major environmental challenges facing the world today?",
        "What are the ethical implications of genetic engineering and cloning?",
        "How do different types of literature reflect and shape cultural values?",
        "What are the causes and effects of natural disasters?",
        "How do different types of artificial intelligence work?",
        "What are the causes and consequences of major economic recessions and depressions?",
        "How does the criminal justice system operate in different countries?",
        "What are the basic principles and techniques used in theater and acting?",
        "What are the major historical and cultural influences on fashion trends?",
        "How do different societies approach and treat mental illness?",
        "What are the causes and effects of major demographic shifts and migration patterns?",
        "How does technology impact privacy and personal information?",
        "What are the major theories and debates in the field of psychology?",
        "How does culture impact language and communication?",
        "What are the basic principles and techniques used in sculpture?",
        "What are the major environmental and health impacts of different agricultural practices?",
        "What are the causes and consequences of major political scandals?",
        "How does different architecture reflect and shape cultural values and needs?",
        "What are the major theories and principles of economics?",
        "How do different cultures and societies view and approach death?",
        "What are the causes and consequences of political polarization?",
        "How do different legal systems operate and impact society?",
        "What are the major cultural and scientific contributions of women?",
        "How does climate change impact natural and human systems?",
        "What are the ethical implications of artificial intelligence and automation?",
        "How do different cultures view and approach love and romance?",
        "What are the major historical and cultural influences on music genres?",
        "How does religion impact political ideologies and policies?",
        "What are the basic principles and techniques used in printmaking?",
        "What are the causes and consequences of mass migrations and refugee crises?",
        "How does media literacy impact public discourse and understanding?",
        "What are the key principles and techniques used in fashion design?",
        "What are the major theories and debates in the field of sociology?",
        "How does different art reflect and shape cultural values and beliefs?",
        "What are the major environmental and health impacts of different transportation systems?",
        "What are the causes and effects of major social and cultural movements?",
        "What are the major historical and cultural influences on architecture?",
        "How does social class impact access to resources and opportunities?",
        "What are the causes and consequences of political corruption?",
        "How does globalization impact cultural exchange and diversity?",
        "What are the major historical and cultural influences on visual art?",
        "How does social identity impact perceptions and experiences of discrimination?",
        "What are the major environmental and health impacts of different energy sources?",
        "What are the ethical implications of animal testing and experimentation?",
        "How do different cultures view and approach education and learning?",
        "What are the major theories and debates in the field of linguistics?",
        "How do different types of media influence public opinion and behavior?"
    ];


    const lifeQuestions = [
        "What are some effective ways to overcome procrastination?",
        "How do I develop a morning routine that helps me start my day off right?",
        "What are some healthy and delicious meal prep ideas for busy people?",
        "What are some tips for reducing stress and anxiety in everyday life?",
        "How can I improve my communication skills in the workplace?",
        "What are some effective study techniques for college students?",
        "How can I manage my time more effectively and get more done in a day?",
        "What are some proven ways to boost productivity and motivation?",
        "How can I improve my public speaking skills and overcome my fear of speaking in public?",
        "What are some simple yet effective ways to improve my mental health and well-being?",
        "What are some practical ways to stay focused and avoid distractions?",
        "What are some good habits to develop to increase your overall happiness?",
        "How can I improve my memory and retention skills?",
        "What are some effective ways to reduce social anxiety and become more confident?",
        "What are some strategies for building strong relationships and connections with others?",
        "How can I learn a new skill quickly and efficiently?",
        "What are some tips for setting and achieving realistic goals?",
        "What are some effective ways to improve your writing skills?",
        "How can I become more financially savvy and start building wealth?",
        "What are some proven methods for overcoming addiction and forming healthy habits?",
        "How can I stay motivated and keep pushing towards my goals when things get tough?",
        "What are some techniques for improving your emotional intelligence and self-awareness?",
        "How can I develop better self-discipline and stick to my goals?",
        "What are some effective ways to network and build connections in your industry?",
        "What are some proven techniques for overcoming imposter syndrome and building self-confidence?",
        "How can I improve my critical thinking and problem-solving skills?",
        "What are some effective ways to handle conflicts in personal and professional relationships?",
        "How can I develop my creativity and come up with innovative ideas?",
        "What are some healthy and effective ways to manage and reduce stress levels?",
        "What are some practical steps for starting and running a successful business?",
        "How can I improve my time management and work more efficiently?",
        "What are some effective ways to improve your leadership skills and manage a team?",
        "What are some tips for maintaining a healthy work-life balance?",
        "What are some effective ways to improve your listening skills and be a better communicator?",
        "How can I develop a positive and growth-oriented mindset?",
        "What are some practical ways to reduce distractions and increase focus?",
        "What are some techniques for improving your memory and retaining information better?",
        "How can I build my confidence and overcome shyness in social situations?",
        "What are some effective ways to boost creativity and come up with new ideas?",
        "How can I build a strong and supportive community of friends and colleagues?",
        "What are some effective ways to improve your negotiation skills?",
        "How can I build better habits and break bad ones?",
        "What are some strategies for building resilience and overcoming adversity?",
        "What are some effective ways to manage stress and anxiety in the workplace?",
        "How can I develop better time management skills and get more done in a day?",
        "What are some proven ways to stay motivated and inspired?",
        "How can I improve my decision-making skills and make better choices?",
        "What are some practical ways to increase your productivity and work smarter?",
        "How can I become a better listener and improve my communication skills?",
        "What are some tips for effective public speaking?",
        "How can I improve my problem-solving skills?",
        "What are some strategies for managing a remote team?",
        "How can I develop my emotional intelligence?",
        "What are some effective ways to handle stress and pressure at work?",
        "What are some techniques for managing anxiety and worry?",
        "How can I build better relationships with my coworkers?",
        "What are some practical ways to improve your memory recall?",
        "How can I improve my listening and comprehension skills?",
        "What are some effective ways to build a strong work ethic?",
        "What are some tips for creating a successful morning routine?",
        "How can I develop better decision-making skills?",
        "What are some proven ways to overcome writer's block?",
        "What are some strategies for managing time when working from home?",
        "How can I become more organized and productive?",
        "What are some techniques for developing a growth mindset?",
        "How can I build better relationships with my family?",
        "What are some effective ways to increase creativity in the workplace?",
        "What are some tips for dealing with difficult people?",
        "How can I develop better negotiation skills?",
        "What are some practical ways to improve your concentration?",
        "What are some effective ways to handle rejection?",
        "How can I improve my problem-solving and decision-making abilities?",
        "What are some strategies for managing conflict in the workplace?",
        "How can I build better relationships with my customers?",
        "What are some effective ways to develop better communication skills?",
        "What are some tips for developing a strong work-life balance?",
        "How can I improve my self-confidence and self-esteem?",
        "What are some techniques for improving memory retention and recall?",
        "What are some effective ways to stay focused and productive when working from home?",
        "How can I build better relationships with my significant other?",
        "What are some strategies for managing a team effectively?",
        "How can I develop better leadership skills?",
        "What are some practical ways to improve your writing speed?",
        "What are some effective ways to handle criticism?",
        "How can I improve my time management skills?",
        "What are some tips for building better habits and breaking bad ones?",
        "What are some techniques for overcoming fear and anxiety?",
        "How can I build better relationships with my children?",
        "What are some effective ways to improve your problem-solving skills at work?",
        "What are some strategies for managing stress and anxiety in your personal life?",
        "How can I develop better conflict resolution skills?",
        "What are some practical ways to increase your creativity outside of work?",
        "What are some effective ways to handle difficult conversations?",
        "How can I improve my memory recall for names and faces?",
        "What are some tips for building a strong personal brand?",
        "What are some techniques for managing stress and anxiety during a job search?",
        "How can I build better relationships with my neighbors?",
        "What are some effective ways to improve your team's morale and motivation?",
        "What are some strategies for managing time when balancing work and school?",
        "How can I develop better customer service skills?",
        "What are some practical ways to improve your concentration when studying?",
        "What are some effective ways to handle change and uncertainty?",
        "How can I improve my critical thinking skills in the workplace?",
        "What are some tips for building better relationships with coworkers outside of work?",
        "What are some techniques for managing stress and anxiety in the classroom?",
        "How can I build better relationships with my roommates?"];
    return { worldQuestions, lifeQuestions };
}