export const lifeQuestions = [
    "What are some effective ways to overcome procrastination?",
    "How do I develop a morning routine that helps me start my day off right?",
    "What are some healthy and delicious meal prep ideas for busy people?",
    "What are some tips for reducing stress and anxiety in everyday life?",
    "How can I improve my communication skills in the workplace?",
    "What are some effective study techniques for college students?",
    "How can I manage my time more effectively and get more done in a day?",
    "What are some proven ways to boost productivity and motivation?",
    "How can I improve my public speaking skills and overcome my fear of speaking in public?",
    "What are some simple yet effective ways to improve my mental health and well-being?",
    "What are some practical ways to stay focused and avoid distractions?",
    "What are some good habits to develop to increase your overall happiness?",
    "How can I improve my memory and retention skills?",
    "What are some effective ways to reduce social anxiety and become more confident?",
    "What are some strategies for building strong relationships and connections with others?",
    "How can I learn a new skill quickly and efficiently?",
    "What are some tips for setting and achieving realistic goals?",
    "What are some effective ways to improve your writing skills?",
    "How can I become more financially savvy and start building wealth?",
    "What are some proven methods for overcoming addiction and forming healthy habits?",
    "How can I stay motivated and keep pushing towards my goals when things get tough?",
    "What are some techniques for improving your emotional intelligence and self-awareness?",
    "How can I develop better self-discipline and stick to my goals?",
    "What are some effective ways to network and build connections in your industry?",
    "What are some proven techniques for overcoming imposter syndrome and building self-confidence?",
    "How can I improve my critical thinking and problem-solving skills?",
    "What are some effective ways to handle conflicts in personal and professional relationships?",
    "How can I develop my creativity and come up with innovative ideas?",
    "What are some healthy and effective ways to manage and reduce stress levels?",
    "What are some practical steps for starting and running a successful business?",
    "How can I improve my time management and work more efficiently?",
    "What are some effective ways to improve your leadership skills and manage a team?",
    "What are some tips for maintaining a healthy work-life balance?",
    "What are some effective ways to improve your listening skills and be a better communicator?",
    "How can I develop a positive and growth-oriented mindset?",
    "What are some practical ways to reduce distractions and increase focus?",
    "What are some techniques for improving your memory and retaining information better?",
    "How can I build my confidence and overcome shyness in social situations?",
    "What are some effective ways to boost creativity and come up with new ideas?",
    "How can I build a strong and supportive community of friends and colleagues?",
    "What are some effective ways to improve your negotiation skills?",
    "How can I build better habits and break bad ones?",
    "What are some strategies for building resilience and overcoming adversity?",
    "What are some effective ways to manage stress and anxiety in the workplace?",
    "How can I develop better time management skills and get more done in a day?",
    "What are some proven ways to stay motivated and inspired?",
    "How can I improve my decision-making skills and make better choices?",
    "What are some practical ways to increase your productivity and work smarter?",
    "How can I become a better listener and improve my communication skills?",
    "What are some tips for effective public speaking?",
    "How can I improve my problem-solving skills?",
    "What are some strategies for managing a remote team?",
    "How can I develop my emotional intelligence?",
    "What are some effective ways to handle stress and pressure at work?",
    "What are some techniques for managing anxiety and worry?",
    "How can I build better relationships with my coworkers?",
    "What are some practical ways to improve your memory recall?",
    "How can I improve my listening and comprehension skills?",
    "What are some effective ways to build a strong work ethic?",
    "What are some tips for creating a successful morning routine?",
    "How can I develop better decision-making skills?",
    "What are some proven ways to overcome writer's block?",
    "What are some strategies for managing time when working from home?",
    "How can I become more organized and productive?",
    "What are some techniques for developing a growth mindset?",
    "How can I build better relationships with my family?",
    "What are some effective ways to increase creativity in the workplace?",
    "What are some tips for dealing with difficult people?",
    "How can I develop better negotiation skills?",
    "What are some practical ways to improve your concentration?",
    "What are some effective ways to handle rejection?",
    "How can I improve my problem-solving and decision-making abilities?",
    "What are some strategies for managing conflict in the workplace?",
    "How can I build better relationships with my customers?",
    "What are some effective ways to develop better communication skills?",
    "What are some tips for developing a strong work-life balance?",
    "How can I improve my self-confidence and self-esteem?",
    "What are some techniques for improving memory retention and recall?",
    "What are some effective ways to stay focused and productive when working from home?",
    "How can I build better relationships with my significant other?",
    "What are some strategies for managing a team effectively?",
    "How can I develop better leadership skills?",
    "What are some practical ways to improve your writing speed?",
    "What are some effective ways to handle criticism?",
    "How can I improve my time management skills?",
    "What are some tips for building better habits and breaking bad ones?",
    "What are some techniques for overcoming fear and anxiety?",
    "How can I build better relationships with my children?",
    "What are some effective ways to improve your problem-solving skills at work?",
    "What are some strategies for managing stress and anxiety in your personal life?",
    "How can I develop better conflict resolution skills?",
    "What are some practical ways to increase your creativity outside of work?",
    "What are some effective ways to handle difficult conversations?",
    "How can I improve my memory recall for names and faces?",
    "What are some tips for building a strong personal brand?",
    "What are some techniques for managing stress and anxiety during a job search?",
    "How can I build better relationships with my neighbors?",
    "What are some effective ways to improve your team's morale and motivation?",
    "What are some strategies for managing time when balancing work and school?",
    "How can I develop better customer service skills?",
    "What are some practical ways to improve your concentration when studying?",
    "What are some effective ways to handle change and uncertainty?",
    "How can I improve my critical thinking skills in the workplace?",
    "What are some tips for building better relationships with coworkers outside of work?",
    "What are some techniques for managing stress and anxiety in the classroom?",
    "How can I build better relationships with my roommates?"
];
   