export const worldQuestions = [
    "What is the origin and evolution of the universe?",
    "How does globalization impact international relations and culture?",
    "What are the ethical implications of emerging technologies?",
    "What is the impact of colonialism and imperialism on the world today?",
    "How does the brain process and interpret information?",
    "What are the causes and effects of biodiversity loss?",
    "What are the major historical events that shaped the modern world?",
    "How do different artistic movements reflect cultural values and beliefs?",
    "What are the basic principles of sports training and performance?",
    "How do animals communicate and interact with each other?",
    "What are the psychological factors that influence human behavior and decision-making?",
    "What are the key principles and techniques used in architecture and urban planning?",
    "How does popular culture reflect and shape societal norms and values?",
    "What are the causes and consequences of income inequality and poverty?",
    "How does the environment impact human health and wellbeing?",
    "What are the key principles and techniques used in music composition and performance?",
    "What are the major political and social movements of the 20th century?",
    "How do different cultures and societies define and value education?",
    "What are the basic principles and techniques used in culinary arts?",
    "How does transportation technology shape urban development and mobility?",
    "What is the nature of consciousness and subjective experience?",
    "How do economic systems impact the distribution of wealth and resources?",
    "What are the major social and cultural issues facing the world today?",
    "How does immigration impact global demographics and culture?",
    "What are the key principles and techniques used in filmmaking?",
    "What are the causes and effects of major pandemics and epidemics?",
    "How does social media shape public opinion and behavior?",
    "What are the causes and consequences of war and conflict?",
    "How do different types of renewable energy sources work?",
    "What are the fundamental principles of mathematics and logic?",
    "How do different cultures view and practice spirituality and religion?",
    "What are the key principles and techniques used in photography?",
    "What are the basic principles and techniques used in graphic design?",
    "How do human rights laws and treaties impact global society?",
    "What are the major cultural and scientific contributions of different civilizations?",
    "What are the key principles and techniques used in dance performance and choreography?",
    "How does globalization impact the environment and natural resources?",
    "What are the causes and consequences of major social and political revolutions?",
    "How do different societies view and approach mental health and wellness?",
    "What are the fundamental principles and techniques used in painting?",
    "What are the cultural and historical roots of different cuisines?",
    "How does gender identity and sexuality influence social dynamics?",
    "What are the major environmental challenges facing the world today?",
    "What are the ethical implications of genetic engineering and cloning?",
    "How do different types of literature reflect and shape cultural values?",
    "What are the causes and effects of natural disasters?",
    "How do different types of artificial intelligence work?",
    "What are the causes and consequences of major economic recessions and depressions?",
    "How does the criminal justice system operate in different countries?",
    "What are the basic principles and techniques used in theater and acting?",
    "What are the major historical and cultural influences on fashion trends?",
    "How do different societies approach and treat mental illness?",
    "What are the causes and effects of major demographic shifts and migration patterns?",
    "How does technology impact privacy and personal information?",
    "What are the major theories and debates in the field of psychology?",
    "How does culture impact language and communication?",
    "What are the basic principles and techniques used in sculpture?",
    "What are the major environmental and health impacts of different agricultural practices?",
    "What are the causes and consequences of major political scandals?",
    "How does different architecture reflect and shape cultural values and needs?",
    "What are the major theories and principles of economics?",
    "How do different cultures and societies view and approach death?",
    "What are the causes and consequences of political polarization?",
    "How do different legal systems operate and impact society?",
    "What are the major cultural and scientific contributions of women?",
    "How does climate change impact natural and human systems?",
    "What are the ethical implications of artificial intelligence and automation?",
    "How do different cultures view and approach love and romance?",
    "What are the major historical and cultural influences on music genres?",
    "How does religion impact political ideologies and policies?",
    "What are the basic principles and techniques used in printmaking?",
    "What are the causes and consequences of mass migrations and refugee crises?",
    "How does media literacy impact public discourse and understanding?",
    "What are the key principles and techniques used in fashion design?",
    "What are the major theories and debates in the field of sociology?",
    "How does different art reflect and shape cultural values and beliefs?",
    "What are the major environmental and health impacts of different transportation systems?",
    "What are the causes and effects of major social and cultural movements?",
    "What are the major historical and cultural influences on architecture?",
    "How does social class impact access to resources and opportunities?",
    "What are the causes and consequences of political corruption?",
    "How does globalization impact cultural exchange and diversity?",
    "What are the major historical and cultural influences on visual art?",
    "How does social identity impact perceptions and experiences of discrimination?",
    "What are the major environmental and health impacts of different energy sources?",
    "What are the ethical implications of animal testing and experimentation?",
    "How do different cultures view and approach education and learning?",
    "What are the major theories and debates in the field of linguistics?",
    "How do different types of media influence public opinion and behavior?"
];

